"""Compatibility facade for extraction rule and agent contracts."""

from dataController.scraper.agent.contracts import (
    EvaluatedNoticeEvidenceV2,
    ExtractedNoticeEvidence,
    MIN_RESULT_PASS_CONFIDENCE,
    ResultEvaluationRequestV1,
    ResultEvaluationRequestV2,
    ResultEvaluationV1,
    ResultEvaluationV2,
    ResultReasonCode,
    RuleValidationMetrics,
    SourceFieldValuesV1,
    SourceRecordEvidenceV1,
    SourceViewCandidateV1,
    SourceViewGroupEvidenceV1,
    SourceViewSelectionRequestV1,
    SourceViewSelectionV1,
    SourceViewStrategy,
    result_evaluation_json_schema,
)
from dataController.scraper.extraction.rules.contracts import (
    ExtractedFieldRules,
    ExtractorRuleV1,
    FieldName,
    FieldRule,
    HtmlFieldRule,
    JsonFieldRule,
    TransformName,
    extractor_rule_json_schema,
)

__all__ = [
    "EvaluatedNoticeEvidenceV2",
    "ExtractedFieldRules",
    "ExtractedNoticeEvidence",
    "ExtractorRuleV1",
    "FieldName",
    "FieldRule",
    "HtmlFieldRule",
    "JsonFieldRule",
    "MIN_RESULT_PASS_CONFIDENCE",
    "ResultEvaluationRequestV1",
    "ResultEvaluationRequestV2",
    "ResultEvaluationV1",
    "ResultEvaluationV2",
    "ResultReasonCode",
    "RuleValidationMetrics",
    "SourceFieldValuesV1",
    "SourceRecordEvidenceV1",
    "SourceViewCandidateV1",
    "SourceViewGroupEvidenceV1",
    "SourceViewSelectionRequestV1",
    "SourceViewSelectionV1",
    "SourceViewStrategy",
    "TransformName",
    "extractor_rule_json_schema",
    "result_evaluation_json_schema",
]
