--
-- PostgreSQL database dump
--

\restrict WAAdHjtdDgbUIplfg1xAYJ1sM6VIguTayVGdB6uQkeWH6hE8C51PjiKm8fpoOHd

-- Dumped from database version 15.16 (Debian 15.16-1.pgdg13+1)
-- Dumped by pg_dump version 15.16 (Debian 15.16-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api (
    api_id integer NOT NULL,
    site_id integer NOT NULL,
    api_url text NOT NULL,
    headers jsonb DEFAULT '{}'::jsonb NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_hash text,
    scraped_at timestamp with time zone,
    method_type character varying(10) DEFAULT 'GET'::character varying NOT NULL,
    extractor_config jsonb,
    schema_hash text,
    last_observed_hash text,
    last_processed_hash text,
    processing_status character varying(20),
    retry_count integer DEFAULT 0 NOT NULL,
    next_retry_at timestamp with time zone,
    last_error text,
    extractor_confidence double precision,
    CONSTRAINT ck_api_extractor_confidence CHECK (((extractor_confidence IS NULL) OR ((extractor_confidence >= (0.0)::double precision) AND (extractor_confidence <= (1.0)::double precision)))),
    CONSTRAINT ck_api_method_type CHECK (((method_type)::text = ANY ((ARRAY['GET'::character varying, 'POST'::character varying, 'PUT'::character varying, 'PATCH'::character varying, 'DELETE'::character varying, 'HEAD'::character varying, 'OPTIONS'::character varying])::text[]))),
    CONSTRAINT ck_api_processing_status CHECK (((processing_status IS NULL) OR ((processing_status)::text = ANY ((ARRAY['success'::character varying, 'valid_empty'::character varying, 'failed'::character varying])::text[])))),
    CONSTRAINT ck_api_retry_count CHECK ((retry_count >= 0))
);


--
-- Name: api_api_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api ALTER COLUMN api_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_api_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crawl_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crawl_runs (
    crawl_run_id bigint NOT NULL,
    site_id integer NOT NULL,
    api_id integer,
    status character varying(20) NOT NULL,
    selection_mode character varying(30),
    processing_mode character varying(30),
    observed_hash text,
    processed_hash text,
    schema_hash text,
    candidate_count integer,
    extracted_notice_count integer,
    llm_used boolean DEFAULT false NOT NULL,
    llm_input_tokens integer,
    llm_output_tokens integer,
    llm_cost numeric(12,6),
    error_code character varying(100),
    error_message text,
    started_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finished_at timestamp with time zone,
    CONSTRAINT ck_crawl_runs_candidate_count CHECK (((candidate_count IS NULL) OR (candidate_count >= 0))),
    CONSTRAINT ck_crawl_runs_extracted_notice_count CHECK (((extracted_notice_count IS NULL) OR (extracted_notice_count >= 0))),
    CONSTRAINT ck_crawl_runs_finished_at CHECK (((finished_at IS NULL) OR (finished_at >= started_at))),
    CONSTRAINT ck_crawl_runs_llm_cost CHECK (((llm_cost IS NULL) OR (llm_cost >= (0)::numeric))),
    CONSTRAINT ck_crawl_runs_llm_input_tokens CHECK (((llm_input_tokens IS NULL) OR (llm_input_tokens >= 0))),
    CONSTRAINT ck_crawl_runs_llm_output_tokens CHECK (((llm_output_tokens IS NULL) OR (llm_output_tokens >= 0)))
);


--
-- Name: crawl_runs_crawl_run_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.crawl_runs ALTER COLUMN crawl_run_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crawl_runs_crawl_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_folders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite_folders (
    folder_id integer NOT NULL,
    user_id integer NOT NULL,
    parent_folder_id integer,
    folder_name character varying(100) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_favorite_folders_not_self_parent CHECK (((parent_folder_id IS NULL) OR (parent_folder_id <> folder_id)))
);


--
-- Name: favorite_folders_folder_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite_folders ALTER COLUMN folder_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_folders_folder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite_notices (
    favorite_id integer NOT NULL,
    folder_id integer NOT NULL,
    notice_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: favorite_notices_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite_notices ALTER COLUMN favorite_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_notices_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: folder_keywords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.folder_keywords (
    keyword_id integer NOT NULL,
    folder_id integer NOT NULL,
    keyword character varying(50) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: folder_keywords_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.folder_keywords ALTER COLUMN keyword_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.folder_keywords_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiries (
    inquiry_id integer NOT NULL,
    user_id integer NOT NULL,
    category character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reply_content text,
    replied_at timestamp with time zone,
    CONSTRAINT ck_inquiries_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying])::text[])))
);


--
-- Name: inquiries_inquiry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inquiries ALTER COLUMN inquiry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inquiries_inquiry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notices (
    notice_id integer NOT NULL,
    site_id integer NOT NULL,
    title text NOT NULL,
    url text NOT NULL,
    scraped_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    author text,
    is_active boolean DEFAULT true NOT NULL,
    detail_url text,
    external_id text,
    published_at timestamp with time zone,
    content_type character varying(30),
    record_hash text
);


--
-- Name: notices_notice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notices ALTER COLUMN notice_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notices_notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referrals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referrals (
    referral_id integer NOT NULL,
    referrer_id integer NOT NULL,
    referee_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_referrals_different_users CHECK ((referrer_id <> referee_id))
);


--
-- Name: referrals_referral_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referrals ALTER COLUMN referral_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referrals_referral_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sites (
    site_id integer NOT NULL,
    site_url text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_viewed_at timestamp with time zone DEFAULT '1970-01-01 09:00:00+09'::timestamp with time zone NOT NULL,
    submitted_url text,
    crawl_status character varying(20),
    validation_status character varying(20),
    validation_error text,
    last_validated_at timestamp with time zone,
    CONSTRAINT ck_sites_crawl_status CHECK (((crawl_status IS NULL) OR ((crawl_status)::text = ANY ((ARRAY['pending'::character varying, 'active'::character varying, 'paused'::character varying, 'failed'::character varying, 'blocked'::character varying])::text[]))))
);


--
-- Name: sites_site_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sites ALTER COLUMN site_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sites_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_fcm_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_fcm_tokens (
    token_id integer NOT NULL,
    user_id integer NOT NULL,
    fcm_token text NOT NULL,
    device_id character varying(100) NOT NULL,
    device_type character varying(20),
    last_updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_fcm_tokens_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_fcm_tokens ALTER COLUMN token_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_fcm_tokens_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_hidden_notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_hidden_notices (
    hidden_id integer NOT NULL,
    user_id integer NOT NULL,
    notice_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_hidden_notices_hidden_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_hidden_notices ALTER COLUMN hidden_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_hidden_notices_hidden_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_subscriptions (
    subscription_id integer NOT NULL,
    user_id integer NOT NULL,
    site_id integer NOT NULL,
    alias character varying(100),
    last_synced_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_subscriptions_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_subscriptions ALTER COLUMN subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_subscriptions_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    social_id character varying(255) NOT NULL,
    provider character varying(20) NOT NULL,
    email character varying(255),
    max_sites_limit integer DEFAULT 5 NOT NULL,
    max_keywords_limit integer DEFAULT 50 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    nickname character varying(20),
    is_notification_enabled boolean DEFAULT false NOT NULL,
    notification_time character varying(10) DEFAULT '18:00'::character varying NOT NULL,
    role character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    CONSTRAINT ck_users_max_keywords_limit CHECK ((max_keywords_limit >= 0)),
    CONSTRAINT ck_users_max_sites_limit CHECK ((max_sites_limit >= 0)),
    CONSTRAINT ck_users_notification_time CHECK (((notification_time)::text ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'::text)),
    CONSTRAINT ck_users_role CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api api_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api
    ADD CONSTRAINT api_pkey PRIMARY KEY (api_id);


--
-- Name: crawl_runs crawl_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawl_runs
    ADD CONSTRAINT crawl_runs_pkey PRIMARY KEY (crawl_run_id);


--
-- Name: favorite_folders favorite_folders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_folders
    ADD CONSTRAINT favorite_folders_pkey PRIMARY KEY (folder_id);


--
-- Name: favorite_notices favorite_notices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_notices
    ADD CONSTRAINT favorite_notices_pkey PRIMARY KEY (favorite_id);


--
-- Name: folder_keywords folder_keywords_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folder_keywords
    ADD CONSTRAINT folder_keywords_pkey PRIMARY KEY (keyword_id);


--
-- Name: inquiries inquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_pkey PRIMARY KEY (inquiry_id);


--
-- Name: notices notices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notices
    ADD CONSTRAINT notices_pkey PRIMARY KEY (notice_id);


--
-- Name: referrals referrals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referrals
    ADD CONSTRAINT referrals_pkey PRIMARY KEY (referral_id);


--
-- Name: sites sites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sites
    ADD CONSTRAINT sites_pkey PRIMARY KEY (site_id);


--
-- Name: api uq_api_site; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api
    ADD CONSTRAINT uq_api_site UNIQUE (site_id);


--
-- Name: favorite_folders uq_favorite_folders_user_folder; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_folders
    ADD CONSTRAINT uq_favorite_folders_user_folder UNIQUE (user_id, folder_id);


--
-- Name: favorite_notices uq_favorite_notices_folder_notice; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_notices
    ADD CONSTRAINT uq_favorite_notices_folder_notice UNIQUE (folder_id, notice_id);


--
-- Name: folder_keywords uq_folder_keywords_folder_keyword; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folder_keywords
    ADD CONSTRAINT uq_folder_keywords_folder_keyword UNIQUE (folder_id, keyword);


--
-- Name: notices uq_notices_site_title; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notices
    ADD CONSTRAINT uq_notices_site_title UNIQUE (site_id, title);


--
-- Name: referrals uq_referrals_referee; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referrals
    ADD CONSTRAINT uq_referrals_referee UNIQUE (referee_id);


--
-- Name: sites uq_sites_site_url; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sites
    ADD CONSTRAINT uq_sites_site_url UNIQUE (site_url);


--
-- Name: user_fcm_tokens uq_user_fcm_tokens_user_device; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_fcm_tokens
    ADD CONSTRAINT uq_user_fcm_tokens_user_device UNIQUE (user_id, device_id);


--
-- Name: user_hidden_notices uq_user_hidden_notices_user_notice; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hidden_notices
    ADD CONSTRAINT uq_user_hidden_notices_user_notice UNIQUE (user_id, notice_id);


--
-- Name: user_subscriptions uq_user_subscriptions_user_site; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT uq_user_subscriptions_user_site UNIQUE (user_id, site_id);


--
-- Name: users uq_users_social_provider; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uq_users_social_provider UNIQUE (social_id, provider);


--
-- Name: user_fcm_tokens user_fcm_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_fcm_tokens
    ADD CONSTRAINT user_fcm_tokens_pkey PRIMARY KEY (token_id);


--
-- Name: user_hidden_notices user_hidden_notices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hidden_notices
    ADD CONSTRAINT user_hidden_notices_pkey PRIMARY KEY (hidden_id);


--
-- Name: user_subscriptions user_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_pkey PRIMARY KEY (subscription_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_crawl_runs_api_started_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_crawl_runs_api_started_at ON public.crawl_runs USING btree (api_id, started_at DESC) WHERE (api_id IS NOT NULL);


--
-- Name: idx_crawl_runs_site_started_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_crawl_runs_site_started_at ON public.crawl_runs USING btree (site_id, started_at DESC);


--
-- Name: idx_crawl_runs_status_started_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_crawl_runs_status_started_at ON public.crawl_runs USING btree (status, started_at DESC);


--
-- Name: idx_favorite_folders_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorite_folders_parent_id ON public.favorite_folders USING btree (parent_folder_id) WHERE (parent_folder_id IS NOT NULL);


--
-- Name: idx_favorite_folders_user_sort; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorite_folders_user_sort ON public.favorite_folders USING btree (user_id, sort_order, created_at);


--
-- Name: idx_favorite_notices_notice_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorite_notices_notice_id ON public.favorite_notices USING btree (notice_id);


--
-- Name: idx_inquiries_user_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inquiries_user_created_at ON public.inquiries USING btree (user_id, created_at DESC);


--
-- Name: idx_notices_published_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notices_published_at ON public.notices USING btree (published_at DESC);


--
-- Name: idx_notices_site_active_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notices_site_active_created_at ON public.notices USING btree (site_id, is_active, created_at DESC);


--
-- Name: idx_referrals_referrer_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_referrals_referrer_id ON public.referrals USING btree (referrer_id);


--
-- Name: idx_user_hidden_notices_notice_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_hidden_notices_notice_id ON public.user_hidden_notices USING btree (notice_id);


--
-- Name: idx_user_subscriptions_site_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_subscriptions_site_id ON public.user_subscriptions USING btree (site_id);


--
-- Name: uq_notices_site_detail_url; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_notices_site_detail_url ON public.notices USING btree (site_id, detail_url) WHERE (detail_url IS NOT NULL);


--
-- Name: uq_notices_site_external_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_notices_site_external_id ON public.notices USING btree (site_id, external_id) WHERE (external_id IS NOT NULL);


--
-- Name: api fk_api_site; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api
    ADD CONSTRAINT fk_api_site FOREIGN KEY (site_id) REFERENCES public.sites(site_id) ON DELETE CASCADE;


--
-- Name: crawl_runs fk_crawl_runs_api; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawl_runs
    ADD CONSTRAINT fk_crawl_runs_api FOREIGN KEY (api_id) REFERENCES public.api(api_id) ON DELETE SET NULL;


--
-- Name: crawl_runs fk_crawl_runs_site; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawl_runs
    ADD CONSTRAINT fk_crawl_runs_site FOREIGN KEY (site_id) REFERENCES public.sites(site_id) ON DELETE CASCADE;


--
-- Name: favorite_folders fk_favorite_folders_parent_same_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_folders
    ADD CONSTRAINT fk_favorite_folders_parent_same_user FOREIGN KEY (user_id, parent_folder_id) REFERENCES public.favorite_folders(user_id, folder_id) ON DELETE CASCADE;


--
-- Name: favorite_folders fk_favorite_folders_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_folders
    ADD CONSTRAINT fk_favorite_folders_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: favorite_notices fk_favorite_notices_folder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_notices
    ADD CONSTRAINT fk_favorite_notices_folder FOREIGN KEY (folder_id) REFERENCES public.favorite_folders(folder_id) ON DELETE CASCADE;


--
-- Name: favorite_notices fk_favorite_notices_notice; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite_notices
    ADD CONSTRAINT fk_favorite_notices_notice FOREIGN KEY (notice_id) REFERENCES public.notices(notice_id) ON DELETE CASCADE;


--
-- Name: folder_keywords fk_folder_keywords_folder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folder_keywords
    ADD CONSTRAINT fk_folder_keywords_folder FOREIGN KEY (folder_id) REFERENCES public.favorite_folders(folder_id) ON DELETE CASCADE;


--
-- Name: inquiries fk_inquiries_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT fk_inquiries_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: notices fk_notices_site; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notices
    ADD CONSTRAINT fk_notices_site FOREIGN KEY (site_id) REFERENCES public.sites(site_id) ON DELETE CASCADE;


--
-- Name: referrals fk_referrals_referee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referrals
    ADD CONSTRAINT fk_referrals_referee FOREIGN KEY (referee_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: referrals fk_referrals_referrer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referrals
    ADD CONSTRAINT fk_referrals_referrer FOREIGN KEY (referrer_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_fcm_tokens fk_user_fcm_tokens_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_fcm_tokens
    ADD CONSTRAINT fk_user_fcm_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_hidden_notices fk_user_hidden_notices_notice; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hidden_notices
    ADD CONSTRAINT fk_user_hidden_notices_notice FOREIGN KEY (notice_id) REFERENCES public.notices(notice_id) ON DELETE CASCADE;


--
-- Name: user_hidden_notices fk_user_hidden_notices_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hidden_notices
    ADD CONSTRAINT fk_user_hidden_notices_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_subscriptions fk_user_subscriptions_site; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT fk_user_subscriptions_site FOREIGN KEY (site_id) REFERENCES public.sites(site_id) ON DELETE CASCADE;


--
-- Name: user_subscriptions fk_user_subscriptions_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_subscriptions
    ADD CONSTRAINT fk_user_subscriptions_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict WAAdHjtdDgbUIplfg1xAYJ1sM6VIguTayVGdB6uQkeWH6hE8C51PjiKm8fpoOHd
