BEGIN;

ALTER TABLE user_subscriptions
    ADD COLUMN IF NOT EXISTS notification_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_user_subscriptions_notification_targets
    ON user_subscriptions (site_id, subscription_id)
    WHERE notification_enabled = TRUE
      AND registration_completed_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS subscription_notification_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id INTEGER NOT NULL,
    crawl_run_id BIGINT NOT NULL,
    site_id INTEGER NOT NULL,
    new_notice_ids INTEGER[] NOT NULL,
    new_notice_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_subscription_notification_events_subscription
        FOREIGN KEY (subscription_id) REFERENCES user_subscriptions(subscription_id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_notification_events_crawl_run
        FOREIGN KEY (crawl_run_id) REFERENCES crawl_runs(crawl_run_id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_notification_events_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE,
    CONSTRAINT uq_subscription_notification_events_run
        UNIQUE (subscription_id, crawl_run_id),
    CONSTRAINT ck_subscription_notification_events_count
        CHECK (new_notice_count > 0 AND new_notice_count = cardinality(new_notice_ids)),
    CONSTRAINT ck_subscription_notification_events_status
        CHECK (status IN ('pending', 'processing', 'sent', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_subscription_notification_events_pending
    ON subscription_notification_events (created_at, event_id)
    WHERE status IN ('pending', 'processing');

CREATE TABLE IF NOT EXISTS subscription_notification_deliveries (
    delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    token_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_subscription_notification_deliveries_event
        FOREIGN KEY (event_id) REFERENCES subscription_notification_events(event_id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_notification_deliveries_token
        FOREIGN KEY (token_id) REFERENCES user_fcm_tokens(token_id) ON DELETE CASCADE,
    CONSTRAINT uq_subscription_notification_deliveries_event_token
        UNIQUE (event_id, token_id),
    CONSTRAINT ck_subscription_notification_deliveries_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_subscription_notification_deliveries_status
        CHECK (status IN ('pending', 'sent', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_subscription_notification_deliveries_pending
    ON subscription_notification_deliveries (next_attempt_at, delivery_id)
    WHERE status IN ('pending', 'failed');

ALTER TABLE users
    DROP CONSTRAINT IF EXISTS ck_users_notification_time;

ALTER TABLE users
    DROP COLUMN IF EXISTS notification_time;

COMMIT;
