"""Version and coverage constants shared across pipeline stages."""

MAX_EXTRACTION_EXPANSION_RATIO = 1.2
MIN_EXTRACTION_COVERAGE_RATIO = 0.5
MIN_RECORDS_FOR_COVERAGE_GATE = 4
NOTICE_IDENTITY_VERSION = 2

__all__ = [
    "MAX_EXTRACTION_EXPANSION_RATIO",
    "MIN_EXTRACTION_COVERAGE_RATIO",
    "MIN_RECORDS_FOR_COVERAGE_GATE",
    "NOTICE_IDENTITY_VERSION",
]
