-- NoticeStore 통합 초기 스키마
-- 대상: PostgreSQL 15+
-- 기준: 260727_schema.sql + docs/DB_테이블_수정안.md
-- 용도: 비어 있는 PostgreSQL 데이터 디렉터리의 최초 초기화

BEGIN;

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    social_id VARCHAR(255) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    max_sites_limit INTEGER NOT NULL DEFAULT 5,
    max_keywords_limit INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nickname VARCHAR(20),
    is_notification_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',

    CONSTRAINT uq_users_social_provider UNIQUE (social_id, provider),
    CONSTRAINT ck_users_max_sites_limit CHECK (max_sites_limit >= 0),
    CONSTRAINT ck_users_max_keywords_limit CHECK (max_keywords_limit >= 0),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE sites (
    site_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_viewed_at TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:00+00',

    submitted_url TEXT,
    crawl_status VARCHAR(20),
    validation_status VARCHAR(20),
    validation_error_code VARCHAR(100),
    validation_error TEXT,
    last_validated_at TIMESTAMPTZ,

    CONSTRAINT uq_sites_site_url UNIQUE (site_url),
    CONSTRAINT ck_sites_crawl_status CHECK (
        crawl_status IS NULL
        OR crawl_status IN ('pending', 'active', 'paused', 'failed', 'blocked')
    )
);

CREATE TABLE api (
    api_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INTEGER NOT NULL,
    api_url TEXT NOT NULL,
    headers JSONB NOT NULL DEFAULT '{}'::jsonb,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_hash TEXT,
    scraped_at TIMESTAMPTZ,
    method_type VARCHAR(10) NOT NULL DEFAULT 'GET',

    extractor_config JSONB,
    schema_hash TEXT,
    last_observed_hash TEXT,
    last_processed_hash TEXT,
    processing_status VARCHAR(20),
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    last_error TEXT,
    extractor_confidence DOUBLE PRECISION,

    CONSTRAINT fk_api_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE,
    CONSTRAINT uq_api_site UNIQUE (site_id),
    CONSTRAINT ck_api_method_type
        CHECK (method_type IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS')),
    CONSTRAINT ck_api_processing_status CHECK (
        processing_status IS NULL
        OR processing_status IN ('success', 'valid_empty', 'failed')
    ),
    CONSTRAINT ck_api_retry_count CHECK (retry_count >= 0),
    CONSTRAINT ck_api_extractor_confidence CHECK (
        extractor_confidence IS NULL
        OR extractor_confidence BETWEEN 0.0 AND 1.0
    )
);

CREATE TABLE notices (
    notice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    scraped_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    detail_url TEXT,
    external_id TEXT,
    published_at TIMESTAMPTZ,
    content_type VARCHAR(30),
    record_hash TEXT,

    CONSTRAINT fk_notices_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_notices_site_external_id
    ON notices (site_id, external_id)
    WHERE external_id IS NOT NULL;

-- external_id가 있으면 그것만으로 공지를 식별한다(레코드마다 detail_url이
-- 고유하다는 보장이 없는 사이트도 있음 - 예: 기관 홈페이지 하나를 여러
-- 공고가 공유). 그래서 이 제약은 external_id가 없는 공지끼리만 적용한다.
CREATE UNIQUE INDEX uq_notices_site_detail_url
    ON notices (site_id, detail_url)
    WHERE detail_url IS NOT NULL AND external_id IS NULL;

CREATE UNIQUE INDEX uq_notices_site_fallback_hash
    ON notices (site_id, record_hash)
    WHERE external_id IS NULL
      AND detail_url IS NULL
      AND record_hash IS NOT NULL;

CREATE INDEX idx_notices_site_active_created_at
    ON notices (site_id, is_active, created_at DESC);

CREATE INDEX idx_notices_published_at
    ON notices (published_at DESC);

CREATE TABLE user_subscriptions (
    subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    site_id INTEGER NOT NULL,
    alias VARCHAR(100),
    last_synced_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registration_completed_at TIMESTAMPTZ,
    notification_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_subscriptions_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE,
    CONSTRAINT uq_user_subscriptions_user_site UNIQUE (user_id, site_id)
);

CREATE INDEX idx_user_subscriptions_site_id
    ON user_subscriptions (site_id);

CREATE INDEX idx_user_subscriptions_notification_targets
    ON user_subscriptions (site_id, subscription_id)
    WHERE notification_enabled = TRUE
      AND registration_completed_at IS NOT NULL;

CREATE TABLE favorite_folders (
    folder_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    parent_folder_id INTEGER,
    folder_name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_favorite_folders_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_favorite_folders_user_folder UNIQUE (user_id, folder_id),
    CONSTRAINT fk_favorite_folders_parent_same_user
        FOREIGN KEY (user_id, parent_folder_id)
        REFERENCES favorite_folders(user_id, folder_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_favorite_folders_not_self_parent
        CHECK (parent_folder_id IS NULL OR parent_folder_id <> folder_id)
);

CREATE INDEX idx_favorite_folders_user_sort
    ON favorite_folders (user_id, sort_order, created_at);

CREATE INDEX idx_favorite_folders_parent_id
    ON favorite_folders (parent_folder_id)
    WHERE parent_folder_id IS NOT NULL;

CREATE TABLE favorite_notices (
    favorite_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id INTEGER NOT NULL,
    notice_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_favorite_notices_folder
        FOREIGN KEY (folder_id) REFERENCES favorite_folders(folder_id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_notices_notice
        FOREIGN KEY (notice_id) REFERENCES notices(notice_id) ON DELETE CASCADE,
    CONSTRAINT uq_favorite_notices_folder_notice UNIQUE (folder_id, notice_id)
);

CREATE INDEX idx_favorite_notices_notice_id
    ON favorite_notices (notice_id);

CREATE TABLE folder_keywords (
    keyword_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id INTEGER NOT NULL,
    keyword VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_folder_keywords_folder
        FOREIGN KEY (folder_id) REFERENCES favorite_folders(folder_id) ON DELETE CASCADE,
    CONSTRAINT uq_folder_keywords_folder_keyword UNIQUE (folder_id, keyword)
);

CREATE TABLE user_hidden_notices (
    hidden_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    notice_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_hidden_notices_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_hidden_notices_notice
        FOREIGN KEY (notice_id) REFERENCES notices(notice_id) ON DELETE CASCADE,
    CONSTRAINT uq_user_hidden_notices_user_notice UNIQUE (user_id, notice_id)
);

CREATE INDEX idx_user_hidden_notices_notice_id
    ON user_hidden_notices (notice_id);

CREATE TABLE inquiries (
    inquiry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    category VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reply_content TEXT,
    replied_at TIMESTAMPTZ,
    site_id INTEGER,
    crawl_run_id BIGINT,
    site_alias VARCHAR(100),
    site_url TEXT,
    site_error_code VARCHAR(100),

    CONSTRAINT fk_inquiries_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_inquiries_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE SET NULL,
    CONSTRAINT ck_inquiries_status
        CHECK (status IN ('PENDING', 'RESOLVED'))
);

CREATE INDEX idx_inquiries_user_created_at
    ON inquiries (user_id, created_at DESC);

CREATE INDEX idx_inquiries_site_created_at
    ON inquiries (site_id, created_at DESC)
    WHERE site_id IS NOT NULL;

CREATE INDEX idx_inquiries_site_error_code
    ON inquiries (site_error_code, created_at DESC)
    WHERE site_error_code IS NOT NULL;

CREATE TABLE referrals (
    referral_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id INTEGER NOT NULL,
    referee_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_referrals_referrer
        FOREIGN KEY (referrer_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_referrals_referee
        FOREIGN KEY (referee_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_referrals_referee UNIQUE (referee_id),
    CONSTRAINT ck_referrals_different_users CHECK (referrer_id <> referee_id)
);

CREATE INDEX idx_referrals_referrer_id
    ON referrals (referrer_id);

CREATE TABLE user_fcm_tokens (
    token_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    fcm_token TEXT NOT NULL,
    device_id VARCHAR(100) NOT NULL,
    device_type VARCHAR(20),
    last_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_fcm_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_user_fcm_tokens_user_device UNIQUE (user_id, device_id)
);

CREATE TABLE crawl_runs (
    crawl_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INTEGER NOT NULL,
    api_id INTEGER,
    status VARCHAR(20) NOT NULL,
    selection_mode VARCHAR(30),
    processing_mode VARCHAR(30),
    observed_hash TEXT,
    processed_hash TEXT,
    schema_hash TEXT,
    candidate_count INTEGER,
    extracted_notice_count INTEGER,
    selection_decision VARCHAR(30),
    selection_reason TEXT,
    selected_candidate_index INTEGER,
    candidate_evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
    review_label VARCHAR(30),
    review_notes TEXT,
    reviewed_by INTEGER,
    reviewed_at TIMESTAMPTZ,
    llm_used BOOLEAN NOT NULL DEFAULT FALSE,
    llm_input_tokens INTEGER,
    llm_output_tokens INTEGER,
    llm_cost NUMERIC(12, 6),
    agent_stage_telemetry JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_activation_status VARCHAR(20),
    rule_activation_reason TEXT,
    evaluator_decision VARCHAR(10),
    evaluator_confidence NUMERIC(5, 4),
    error_code VARCHAR(100),
    error_message TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,

    CONSTRAINT fk_crawl_runs_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE,
    CONSTRAINT fk_crawl_runs_api
        FOREIGN KEY (api_id) REFERENCES api(api_id) ON DELETE SET NULL,
    CONSTRAINT fk_crawl_runs_reviewer
        FOREIGN KEY (reviewed_by) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT ck_crawl_runs_candidate_count
        CHECK (candidate_count IS NULL OR candidate_count >= 0),
    CONSTRAINT ck_crawl_runs_extracted_notice_count
        CHECK (extracted_notice_count IS NULL OR extracted_notice_count >= 0),
    CONSTRAINT ck_crawl_runs_selection_decision CHECK (
        selection_decision IS NULL
        OR selection_decision IN (
            'accept_rule',
            'defer_to_llm',
            'reject_or_observe_more',
            'cached_reuse'
        )
    ),
    CONSTRAINT ck_crawl_runs_selected_candidate_index
        CHECK (
            selected_candidate_index IS NULL
            OR selected_candidate_index >= -1
        ),
    CONSTRAINT ck_crawl_runs_review_label CHECK (
        review_label IS NULL
        OR review_label IN (
            'correct',
            'incorrect',
            'no_valid_candidate',
            'needs_more_observation'
        )
    ),
    CONSTRAINT ck_crawl_runs_llm_input_tokens
        CHECK (llm_input_tokens IS NULL OR llm_input_tokens >= 0),
    CONSTRAINT ck_crawl_runs_llm_output_tokens
        CHECK (llm_output_tokens IS NULL OR llm_output_tokens >= 0),
    CONSTRAINT ck_crawl_runs_llm_cost
        CHECK (llm_cost IS NULL OR llm_cost >= 0),
    CONSTRAINT ck_crawl_runs_rule_activation_status CHECK (
        rule_activation_status IS NULL
        OR rule_activation_status IN ('approved', 'rejected', 'failed', 'reused')
    ),
    CONSTRAINT ck_crawl_runs_evaluator_decision CHECK (
        evaluator_decision IS NULL OR evaluator_decision IN ('pass', 'fail')
    ),
    CONSTRAINT ck_crawl_runs_evaluator_confidence CHECK (
        evaluator_confidence IS NULL
        OR evaluator_confidence BETWEEN 0 AND 1
    ),
    CONSTRAINT ck_crawl_runs_finished_at
        CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX idx_crawl_runs_site_started_at
    ON crawl_runs (site_id, started_at DESC);

CREATE INDEX idx_crawl_runs_api_started_at
    ON crawl_runs (api_id, started_at DESC)
    WHERE api_id IS NOT NULL;

CREATE INDEX idx_crawl_runs_status_started_at
    ON crawl_runs (status, started_at DESC);

CREATE INDEX idx_crawl_runs_review_queue
    ON crawl_runs (started_at DESC)
    WHERE review_label IS NULL;

CREATE TABLE subscription_notification_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id INTEGER NOT NULL,
    crawl_run_id BIGINT NOT NULL,
    site_id INTEGER NOT NULL,
    new_notice_ids INTEGER[] NOT NULL,
    new_notice_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_subscription_notification_events_subscription
        FOREIGN KEY (subscription_id) REFERENCES user_subscriptions(subscription_id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_notification_events_crawl_run
        FOREIGN KEY (crawl_run_id) REFERENCES crawl_runs(crawl_run_id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_notification_events_site
        FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE,
    CONSTRAINT uq_subscription_notification_events_run
        UNIQUE (subscription_id, crawl_run_id),
    CONSTRAINT ck_subscription_notification_events_count
        CHECK (new_notice_count > 0 AND new_notice_count = cardinality(new_notice_ids)),
    CONSTRAINT ck_subscription_notification_events_status
        CHECK (status IN ('pending', 'processing', 'sent', 'cancelled'))
);

CREATE INDEX idx_subscription_notification_events_pending
    ON subscription_notification_events (created_at, event_id)
    WHERE status IN ('pending', 'processing');

CREATE TABLE subscription_notification_deliveries (
    delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    token_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_subscription_notification_deliveries_event
        FOREIGN KEY (event_id) REFERENCES subscription_notification_events(event_id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_notification_deliveries_token
        FOREIGN KEY (token_id) REFERENCES user_fcm_tokens(token_id) ON DELETE CASCADE,
    CONSTRAINT uq_subscription_notification_deliveries_event_token
        UNIQUE (event_id, token_id),
    CONSTRAINT ck_subscription_notification_deliveries_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_subscription_notification_deliveries_status
        CHECK (status IN ('pending', 'sent', 'failed', 'cancelled'))
);

CREATE INDEX idx_subscription_notification_deliveries_pending
    ON subscription_notification_deliveries (next_attempt_at, delivery_id)
    WHERE status IN ('pending', 'failed');

ALTER TABLE inquiries
    ADD CONSTRAINT fk_inquiries_crawl_run
    FOREIGN KEY (crawl_run_id)
    REFERENCES crawl_runs(crawl_run_id) ON DELETE SET NULL;

COMMIT;
