// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6J7QPz2B5fsGIbrcIQmczng1nmDNN9c',
    appId: '1:755718526897:web:b3d62f9389c891523acf90',
    messagingSenderId: '755718526897',
    projectId: 'notice-store',
    authDomain: 'notice-store.firebaseapp.com',
    storageBucket: 'notice-store.firebasestorage.app',
    measurementId: 'G-LHX2RVFVZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxwADgvfZrIX5a3tXCbCkHGLNdtA1qj8',
    appId: '1:755718526897:android:cb56ac509ddc5b483acf90',
    messagingSenderId: '755718526897',
    projectId: 'notice-store',
    storageBucket: 'notice-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0o-W-WX3o_J_aAhHGienaM36LuzpPyE',
    appId: '1:755718526897:ios:6f5a9e454414aa8d3acf90',
    messagingSenderId: '755718526897',
    projectId: 'notice-store',
    storageBucket: 'notice-store.firebasestorage.app',
    iosBundleId: 'com.noticestore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0o-W-WX3o_J_aAhHGienaM36LuzpPyE',
    appId: '1:755718526897:ios:b5e6e2b4ce5f5edf3acf90',
    messagingSenderId: '755718526897',
    projectId: 'notice-store',
    storageBucket: 'notice-store.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH6J7QPz2B5fsGIbrcIQmczng1nmDNN9c',
    appId: '1:755718526897:web:3ef13fcebb5ae4083acf90',
    messagingSenderId: '755718526897',
    projectId: 'notice-store',
    authDomain: 'notice-store.firebaseapp.com',
    storageBucket: 'notice-store.firebasestorage.app',
    measurementId: 'G-Y5C41BVKC5',
  );
}
